services:
  db:
    image: postgres:16-alpine
    container_name: elysium-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "elysium"
      POSTGRES_PASSWORD: "Gscob@1996"
      POSTGRES_DB: "elysiumdb"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - elysium-pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elysium-backend-app
    container_name: elysium-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    command: >
      sh -lc 'exec gunicorn
      -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-2}
      -b 0.0.0.0:8080
      main:app'

volumes:
  elysium-pgdata:
