version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: elysium-postgres
    restart: always
    env_file:
      - .env
    # Mapeia nomes esperados pela imagem do Postgres a partir do .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /srv/elysium/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elysium-backend-app
    container_name: elysium-backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      gunicorn -k uvicorn.workers.UvicornWorker main:app
      -b 0.0.0.0:8080
      --workers ${WEB_CONCURRENCY:-2}
