services:
  db:
    image: postgres:16-alpine
    container_name: elysium-postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - elysium-pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - >
          pg_isready
          -h 127.0.0.1
          -p "$${POSTGRES_PORT:-5432}"
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elysium-backend-app
    container_name: elysium-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    command: >
      sh -lc 'exec gunicorn
      -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-2}
      -b 0.0.0.0:8080
      main:app'

volumes:
  elysium-pgdata:
