version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: elysium-postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - elysium-pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  app:
    build: .
    container_name: elysium-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: >
      sh -lc 'exec gunicorn main:app
      -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-2}
      -b 0.0.0.0:8080'

volumes:
  elysium-pgdata:
