services:
  db:
    image: postgres:16-alpine
    container_name: elysium-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /srv/elysium/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elysium-backend-app
    container_name: elysium-backend
    restart: always
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
