# fly.toml — BACKEND (FastAPI/Uvicorn)
app = "elysium-backend-icy-sun-9505"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

  # Liveness: não bate no DB
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "GET"
    path = "/health"
    protocol = "http"

  # Readiness: testa Postgres
  [[http_service.checks]]
    interval = "1m0s"
    timeout = "3s"
    grace_period = "40s"
    method = "GET"
    path = "/api/infra/healthcheck_postgres"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
